yelp-clone/config/routes.rb
Rails.application.routes.draw do

  resources :restaurants

  get 'restaurants/new'

  get 'welcome/index'

  root 'welcome#index'

end

yelp-clone/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

yelp-clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

yelp-clone/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    @restaurant.save
    redirect_to @restaurant
  end

private
    def restaurant_params
      params.require(:restaurant).permit(:name, :description)
    end
end

yelp-clone/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

yelp-clone/app/helpers/application_helper.rb
module ApplicationHelper
end

yelp-clone/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

yelp-clone/app/helpers/welcome_helper.rb
module WelcomeHelper
end

yelp-clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

yelp-clone/app/views/restaurants/new.html.erb
<h1>List a new Restaurant</h1>

<%= form_for :restaurant, url: restaurants_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

yelp-clone/app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

yelp-clone/app/views/welcome/index.html.erb
<h1>Hello Rails!</h1>
<p>Find me in app/views/welcome/index.html.erb</p>